version: '3.8'

services:
  backend:
    container_name: app-backend  # Уникальное имя
    build: ./api
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=1
      - DB_NAME=support_lk_db
    depends_on:
      db:
        condition: service_healthy

  frontend:
    container_name: app-frontend  # Уникальное имя
    build: ./front
    ports:
      - "5173:80"
    depends_on:
      - backend

  db:
    container_name: app-db  # Уникальное имя
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: 1
      POSTGRES_USER: postgres
      POSTGRES_DB: support_lk_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: